# Generated by Django 3.2.15 on 2022-08-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='number',
            field=models.IntegerField(default=None),
        ),
    ]
